translation:
    locales: ["en", "fr"]
    edit_in_place:
        enabled: false
        config_name: app
    configs:
        app:
            dirs: ["%kernel.project_dir%/Resources/templates", "%kernel.project_dir%/src"]
            output_dir: "%kernel.project_dir%/Resources/translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
