framework:
    default_locale: '%locale%'
    translator:
        paths:
            - '%kernel.project_dir%/Resources/translations/forum'
            - '%kernel.project_dir%/Resources/translations/admin'
        fallbacks: ['en', 'fr']
