version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - php
      - mysqldb
  php:
    build:
      context: ./docker/php/
      args:
        TIMEZONE: ${TIMEZONE}
    restart: always
    volumes:
      - ./:/var/www/
  mysqldb:
    image: mysql:5.7
    container_name: ${DATABASE_HOST}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PWD}
      - MYSQL_ROOT_HOST=%
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    volumes:
      - ./shared/db:/var/lib/mysql
