base:
  path: /
  controller: App\Controller\Forum\HomeController::index

cat:
  path: /category/
  controller: App\Controller\Forum\ForumController::index

cat_show:
  path: /category/{slug}
  controller: App\Controller\Forum\CatController::show

forum:
  path: /forum/
  controller: App\Controller\Forum\ForumController::index

forum_show:
  path: /forum/{slug}
  controller: App\Controller\Forum\ForumController::show

topic:
  path: /topic/
  controller: App\Controller\Forum\TopicController::index

topic_show:
  path: /topic/{slug}
  controller: App\Controller\Forum\TopicController::show

faq:
  path: faq
  controller: App\Controller\Forum\FaqController::index