base:
  path: /
  controller: App\Controller\Forum\HomeController::index

forum:
  path: /forum/
  controller: App\Controller\Forum\ForumCOntroller::index

forum_show:
  path: /forum/{slug}
  controller: App\Controller\Forum\ForumController::show